# Generated by Django 6.0.3 on 2026-04-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('city', models.CharField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
