# Generated by Django 6.0.3 on 2026-05-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
    ]
